name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: sersh/golang-builder:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Install libsass dependencies
      run: |
        cd src
        CGO_LDFLAGS="-static" go install github.com/wellington/go-libsass
        
    - name: Build Linux binary
      run: |
        mkdir -p bin
        cd src
        CGO_ENABLED=1 CGO_LDFLAGS="-static" go build -buildvcs=false \
          --ldflags='-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -extldflags=-static' \
          -o ../bin/totaltube-frontend .

    - name: Build FreeBSD binary
      run: |
        cd src
        CGO_ENABLED=1 CGO_LDFLAGS="-static" GOOS=freebsd GOARCH=amd64 CC=clang-freebsd CXX=clang-freebsd go build -buildvcs=false \
          --tags="netgo osusergo" \
          --ldflags='-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -extldflags=-static' \
          -o ../bin/totaltube-frontend-freebsd-amd64 .
          
    - name: Build Windows binary
      run: |
        cd src
        CGO_ENABLED=1 CGO_LDFLAGS="-static" GOOS=windows GOARCH=amd64 \
          CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -buildvcs=false \
          --ldflags='-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -extldflags=-static' \
          -o ../bin/totaltube-frontend.exe .
          
    - name: Create Linux archive
      run: |
        cd bin
        tar --owner=root --group=root --mode='a+rwX' -zcf totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz totaltube-frontend

    - name: Create FreeBSD archive
      run: |
        cd bin
        cp totaltube-frontend-freebsd-amd64 totaltube-frontend
        tar --owner=root --group=root --mode='a+rwX' -zcf totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-freebsd-amd64.tar.gz totaltube-frontend
        rm totaltube-frontend
        
    - name: Create Windows archive
      run: |
        cd bin
        zip totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip totaltube-frontend.exe
        
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## Changes in version ${{ steps.get_version.outputs.VERSION }}
          
          - Built from commit ${{ github.sha }}
          - Linux, FreeBSD and Windows binaries included
        files: |
          ./bin/totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
          ./bin/totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-freebsd-amd64.tar.gz
          ./bin/totaltube-frontend-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip 